spring:
  application:
    name: GraphQl-Demo

  datasource:
    url: jdbc:mysql://localhost:3306/your_db_name
    username: your_db_username
    password: your_db_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  graphql:
    enabled: true
    path: /graphql

server:
  port: 9090
